# Nama aplikasi
spring.application.name=Inventory

# Menonaktifkan autoconfiguration untuk DataSource (agar tidak memerlukan koneksi database)
# spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

# Konfigurasi lokasi view JSP
spring.mvc.view.prefix=/WEB-INF/views/
spring.mvc.view.suffix=.jsp

# Konfigurasi folder static
spring.mvc.static-path-pattern=/static/**
spring.resources.static-locations=classpath:/static/

# Konfigurasi koneksi database MariaDB
spring.datasource.url=jdbc:mariadb://127.0.0.1:3306/inventory
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Hibernate settings untuk MariaDB
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
# spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MariaDBDialect

# Menonaktifkan open-in-view
spring.jpa.open-in-view=false

spring.main.allow-bean-definition-overriding=true



# Set logging level to DEBUG
# logging.level.org.springframework=DEBUG
# logging.level.com.proj.inventory=DEBUG
